### ISSUE TITLE
Erklärung mathematische Vorgehensweise

### ISSUE THREAD

**Issue by leon1995** [pheagan/AYTO-Berechnung#1]
Moin,

gibt es ein Dokument, wo du erklärst was du warum mathematisch machst, damit man das ganze leichter nachvollziehen kann? Wenn ja, würdest du es mit uns teilen?

Vielen Dank!

**Comment by pheagan** [comment]
Hey, ich hatte mal am Anfang für mich ein paar Sachen erstellt, aber nichts was irgendwie sauber dokumentiert ist bzw. was ich so teilen möchte. Vielleicht mach ich das die Tage nochmal sauber anhand des Skripts wie es jetzt ist.
In kurz kann ich aber sagen: Das ist mehr ein Bruteforce Ansatz, erstmal keine Strategie/Logik um Sachen vorab auszuschließen. Heißt, ich generiere alle Kombinationen der 10x10+1 Matching-Möglichkeiten und schau dann für jede Kombination, ob die mit den bekannten Randbedingungen (sind alle bekannten Matches enthalten, stimmt Anzahl der Lichter bei den Matching-Nights überein, ...) kompatibel ist. Am Ende zähle ich dann alle möglichen Kombinationen zusammen und schau für die Tabelle, wer in wie viel Fällen zusammen sitzt.

**Comment by leon1995** [comment]
Achso okay. Schade, weil ich es so doch etwas schwer finde dem Errechnen der Werte zu folgen und nach zu vollziehen, ob das ganz so richtig ist 😅 aber ich geb mein bestes :D

**Comment by pheagan** [comment]
Hab mal meine eigenen Notizen sauber zusammengefasst als Erklärung:
https://github.com/pheagan/AYTO-Berechnung/blob/main/AYTO_Berechnung/Erkl%C3%A4rung_Skript.pdf

**Comment by leon1995** [comment]
Okay danke, ich werd sie mir mal anschauen
