### ISSUE TITLE
Staffel 5 -- Achtung Spoiler (ist aber eingeklappt)

### ISSUE THREAD

**Issue by atticus-sullivan** [pheagan/AYTO-Berechnung#2]
Hi, lang ist es her :smile:

seitdem lief ja auch schon Staffel 5 und ich fang grad an die zu schauen und bin grad dabei meinen Code anzupassen. Hast du @pheagan die schon gesehen? Wenn ichs richtig sehe hast du für die Staffel zumindest noch nichts hochgeladen oder?

Tbh bin ich aber eh hauptsächlich wegen einer Auslegungs-/Interpretationssache hier:

<details><summary>Achtung Spoiler zu Folge 7</summary>

In Folge 7 kommt ja eine neue rein, und es wird bekannt gegeben, dass nun einer drei (statt zuvor zwei matches hat). Würdest du das so auslegen, dass die neue bei dem triple match dabei ist, oder dass das ein komplett random triple ist?

> [...]
> Das ist eure neue Mitbewohnerin xyz.
> Und es gibt noch ein nicht so unwichtiges Detail. Bisher gab es ja hier nen Mann mit 2 perfect matches, jetzt hat der Mann 3 perfect matches.

Bin mir da n bissl unschlüssig.
An sich ist es halt Folge 7 also ja dann doch nicht so ganz am Anfang. Das könnte dafür sprechen, dass sie es nicht ganz so schwer machen und eher auf ersteres gehen (die neue ist in dem triple enthalten).

Von der Wortwahl bei der MN danach denke ich aber glaub, dass die neue in dem triple enthalten ist (und rechne das aktuell so)

<details><summary>Spoiler für das Resultat</summary>

Hab mich schon ganz spoilern lassen und die neue ist tatsächlich in dem Triple enthalten. Es kann also wirklich beides sein und das selbst das Endergebnis hilft nicht beim Entscheiden.

</details>

</details> 

Was sind denn deine (andere sind natürlich auch herzlichst eingeladen mitzuschreiben, aber ich vermute mal jemand andres liest das hier nicht) Gedanken dazu? (Hint: So einklappbare Teile kann man bei Github durch `/detail` am Zeilenanfang generieren lassen falls du das hierunter für notwendig erachtest)

**Comment by atticus-sullivan** [comment]
Ok hat sich im Nachhinein/weiterem Verlauf geklärt. Es ist auf jeden Fall ersteres.

**Comment by pheagan** [comment]
Hey, jein hatte Staffel 5 mal reingeschaut, aber nicht wirklich geguckt. Und ich hatte meinen Code auf Pfush-Ebene bissle angepasst aber weil da theoretisch so viele Möglichkeiten dazu kamen (bevor gesagt wurde dass es ein Tripple-Match gibt) lief die Berechnung ewig und habs nie laufen lassen. Und nachdem es gesagt wurde habe ich es hart gecoded und nur für Ergebnisse laufen lassen (auf Discord gepostet - da im Wiki aber Matching Nights falsch einegtragen waren, hatte ich dann auch ein falsches Ergebnis) Und hab dann die Änderung verworfen und alles weggeschmissen weil ich mir auch dachte "die machen das eh nicht nochmal so, und so wie ich es jetzt hab kann ichs auch gleich nochmal sauber machen"

**Comment by atticus-sullivan** [comment]
Ah ja stimmt den Discord gabs ja auch noch, auf den muss ich auch mal drauf schaun.

Ja gut mit falschen Daten kanns ja nix werden ^^. Wenn du magst und Interesse besteht kannst die Daten auch bei mir klaun, die sollten soweit stimmen (zumindest geht die Berechnung (aufs richtige) auf bei mir).

Gut, wenn man nur die Personen hat ohne die zugehörigen Regeln ja dann werden es total viele Möglichkeiten. Das lustige ist, wenn man die Regeln so wie sie jetzt dann waren (triple match mit der neuen/dritten Person fix als Teil des Triple matches) bleibt die Anzahl der Möglichkeiten einfach gleich :laughing: (hab aber am Anfang auch nicht drüber nachgedacht, erst als ich später am Ausrechnen der Anzahl war weil meine Implementierung das braucht (nicht notwendigerweise eigentlich glaub, aber aktuell halt schon). Und selbst da hab ich ganz blind angefangen n bissl Beispiele aufzuschreiben am Anfang :see_no_evil: )
